version: "3.8"
services:
    flask_api:
        container_name: flask_api
        image: ghcr.io/gchacaltana/flask_api:1.1.1
        extra_hosts:
        - host.docker.internal:host-gateway
        ports:
         - 5000:5000
        network_mode: "host"
        environment:
        - GUNICORN=true
        - DEBUG=true
        - APP_NAME=""
        - APP_VERSION="1.1.1"
        - APP_HOST="localhost"
        - APP_PORT=5000
        - JWT_SECRET_KEY=""
        - JWT_EXPIRES_MIN=""
        - DB_URI=""
        - PAGINATE_PER_PAGE=10
